CREATE ROLE sctbrowser LOGIN
  ENCRYPTED PASSWORD 'md585dd44c055406482ed747b728640c18a'
  SUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE DATABASE sctbrowser
  WITH ENCODING='SQL_ASCII'
       OWNER=sctbrowser
       TEMPLATE=template0
       LC_COLLATE='POSIX'
       LC_CTYPE='POSIX'
       CONNECTION LIMIT=-1;
